name: Cart Service

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run test
        run: mvn clean test -Dspring.profile.active=test

      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cart-service:v1 .

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cart-service:v1